### ISSUE TITLE
data object missing from InteractionManager

### ISSUE THREAD

**Issue by tjgionet** [pixijs/pixi-display#13]
this was fixed in pixi.js as addressed in 
"Make Interaction events closer to Browser behavior #3963"
and originally in 
"Expose event properties on InteractionData (originally from #3890)"

exception thrown in pixi.js line 34546 
"InteractionManager.prototype.processPointerMove = function processPointerMove(interactionEvent, displayObject, hit) {
			var data = interactionEvent.data;
" 
with interactionEvent.data being undefined. 

again at pixi.js 34614
"InteractionManager.prototype.processPointerOverOut = function processPointerOverOut(interactionEvent, displayObject, hit) {
			var data = interactionEvent.data;
"
for the same reason. 

thanks

**Comment by ivanpopelyshev** [comment]
I think that was fixed just after you posted it.
