### ISSUE TITLE
lib/pixi.js/index.d.ts was outdated

### ISSUE THREAD

**Issue by arzyu** [pixijs/pixi-display#15]
Since several interfaces have renamed from "types/pixi.js" v4.5.0+, lib/pixi.js/index.d.ts was outdated in this repo.
When I'm using pixi-layers with "types/pixi.js" v4.5.0+, there will be an error in my console:

```
ERROR in [at-loader] ./node_modules/pixi-layers/bin/pixi-layers.d.ts:99:35
    TS2694: Namespace 'PIXI' has no exported member 'IDestroyOptions'.
```

**Comment by ivanpopelyshev** [comment]
Fixed.
