### ISSUE TITLE
Amplified Exceptions?

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi-display#2]
So one of the most common exceptions of PIXI is going outside the texture boundaries with a frame

I think pixi-display might be amplifying the situation when this happens, the exception is replicated by pixi-display, things freeze

I don't know whether anything can or should be done about this, just sharing my experience - the solution is obviously to hunt and prevent exceptions

**Comment by ivanpopelyshev** [comment]
Can you explain how exactly do you use Texture interface? it might be connected with how we changed it in v4.

**Comment by kaansoral** [comment]
This is my dirtiest usage:
```
animation.sprite.texture.frame=new PIXI.Rectangle(animation.sprite.texture.frame.x+animation.sprite.texture.frame.width,animation.sprite.texture.frame.y,animation.sprite.texture.frame.width,animation.sprite.texture.frame.height);
```
I had a bug where pushed this sliding animation outside it's boundaries, at that point the issue I explained occurred

I can now comment out pixi-display import and see whether the issues I see are emanating from pixi-display, none of them are

At the time of this issue, I didn't have this ability, so I can't verify whether pixi-display made the issue "worse" or "same"

We might close this issue, or I might replicate the problem for the sake of science

**Comment by ivanpopelyshev** [comment]
Its better to create multiple textures and switch between them, than use one texture to slide. That way you'll detect all errors before you start rendering.

**Comment by ivanpopelyshev** [comment]
Also, are you using scale.x=-1 to flip the character? Please look at http://pixijs.github.io/examples/index.html?s=demos&f=texture-rotate.js&title=Texture%20Rotate&v=dev , I made is specially for that cause.

**Comment by kaansoral** [comment]
I do texture reusal for map tiles, yet it didn't occur to me to do it for character sprites and other stuff, I just shift the frame, seems easier

My concern is generally performance (as exceptions manifest themselves during testing)
If pre-generating texture's and switching texture's performs better I might do that

---

I don't do rotations yet, didn't need to, yet I want to do that for some weapon/armor sprites

I guess I will look at that example and try to turn it into a simple function, like rotate(sprite,num)
As it will be done once, the performance doesn't matter, and the example seemed to complex to apply in line, on a sprite by sprite basis, better to put the complexities in a function that will be simple to use

I guess I will give it a go now

**Comment by ivanpopelyshev** [comment]
Strange. Anyway, switching texture of sprite is better for performance, but only a bit. It's just intended behaviour ;)
