### ISSUE TITLE
pixi loader 'normal map'

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-display#30]
hi @ivanpopelyshev , i know you're really busy, but i just want tell you that the dev from [texturePacker](https://www.codeandweb.com/texturepacker/download) just add new update to v4.7 for support **normal map** and make easy to manage in pixi loader.
> Version 4.7.0 (2018-05-09)
> Features
> Added support for FaceBook AR Studio
> **Added normal_map reference to json file's meta section (Pixi, Phaser, Generic)**
> Enabled support for rotated sprites in Phaser

So now the **meta** has a new property called **normal_map:**
That will allow the loader to detect and make special textures tag.
![image](https://user-images.githubusercontent.com/24865815/40069500-89b27cbc-5839-11e8-8499-0fed3d9b8262.png)

do you think you will have the time to update this soon ?
thank a lot for all your work my friend.

**Comment by ivanpopelyshev** [comment]
oh WOW, thanks!

**Comment by ivanpopelyshev** [comment]
now i have to make a loader for it and hook in pixi-spine and in spritesheets

**Comment by djmisterjon** [comment]
keep me informed about your approach for textures , I look forward to seeing how you will manages normal textures.
From my side for now I create clown of textures named "textureName"+"_n".
And to avoid use to complex regex, i case the options "trim Sprite Name"

![image](https://user-images.githubusercontent.com/24865815/40073755-ba7c85ac-5845-11e8-9a61-eef80957abd2.png)

But with this update you will certainly have a new better good idea on the way to approach normal textures.
I can not wait to see it.
thank for all your work.
