### ISSUE TITLE
Render resolution

### ISSUE THREAD

**Issue by evgkfx** [pixijs/pixi-display#39]
Hello I'm trying to pass resolution param in that example https://pixijs.io/examples/#/layers/normals.js, for correct support retina and etc.

```
 const options = {
    width,
    height,
    resolution: window.devicePixelRatio || 1
};

const app = new PIXI.Application(options);
document.body.appendChild(app.view);
...
```
But unfortunately cursor position is incorrect detected. Could you please chech it.
Thanks!

**Comment by evgkfx** [comment]
any ideas?

**Comment by ivanpopelyshev** [comment]
what about autoResize, CSS set width/height, like pixi does it?

**Comment by ivanpopelyshev** [comment]
OK, I put this in example, and it doesn't work:

```
var app = new PIXI.Application(WIDTH, HEIGHT, {resolution:2, autoResize:true});
```

I guess something is wrong with `getRenderTexture()` for this plugin. Unfortunately, I do not have time to investigate it because I'm working on v5 release.

**Comment by TombolaShepless** [comment]
@evgkfx did you ever find a work around to this issue? We're faving the same and would really like to us some nice lighting effects

**Comment by ivanpopelyshev** [comment]
Still working on v5.

@TombolaShepless getRenderTexture() code is not that difficult, you can try to debug that stuff

**Comment by TombolaShepless** [comment]
@ivanpopelyshev I'm pretty new to PIXI so I'm trying. So far I've found that the invocation of `PIXI.RenderTexture.create()` is not passing the right arguments, its currently passing:

```js
this.renderTexture = PIXI.RenderTexture.create(width, height, resolution);
```

but according to the PIXI docs, `resolution` is the 4th arg and the 3rd is `SCALE_MODE`. I've updated the code to:

```js
this.renderTexture = PIXI.RenderTexture.create(width, height, PIXI.settings.SCALE_MODE, resolution);
```

but the output is the same. Not sure where to go from here TBH

**Comment by TombolaShepless** [comment]
Step through it pretty much line-by-line and I can't for the life of me see what else could be wrong other than the above. Any more pointers in a general direction @ivanpopelyshev ?

**Comment by ivanpopelyshev** [comment]
You've done the ritual. I'm looking at it.

**Comment by TombolaShepless** [comment]
Thanks bud, I really appreciate the help. Sorry I couldn't be more use 😞

**Comment by ivanpopelyshev** [comment]
Actually your fix works, @TombolaShepless . But it doesnt work with pixi-lights. Do you need it with pixi-lights?

**Comment by TombolaShepless** [comment]
Yeah with pixi-lights. Do you know why it doesn't work?

**Comment by ivanpopelyshev** [comment]
Of course! it has one uniform in light shader that means both "size in pixels" and "size in CSS" :)

**Comment by TombolaShepless** [comment]
[this?](https://github.com/pixijs/pixi-lights/blob/d83486ce25c2fd7405cbd86d82f7cdd42c7d8c67/src/lights/light/LightShader.js#L23)

I have no idea what to change there - thats far beyond my knowledge and understanding lol

**Comment by ivanpopelyshev** [comment]
Here, try change resolution: https://pixijs.io/examples/#/layers/normals-drag.js

It uses https://pixijs.io/examples/pixi-plugins/pixi-lights.js and https://pixijs.io/examples/pixi-plugins/pixi-layers.js

I'll republish layers now, as for lights, we'll have to wait someone else

**Comment by ivanpopelyshev** [comment]
Yeah, you've found whats wrong with pixi-layers, good job!

As for lights improvement, i'll do it after v5 release and after i move layers to v5. There'll be new demos!

Lights are experimental stuff, its very hard to add them as well as other experimental plugins: projections, heaven. @djmisterjon knows more than others about it. Do you want an invite to pixijs slack? send me an email if you want it.
