### ISSUE TITLE
Support for pixi v5

### ISSUE THREAD

**Issue by jkanchelov** [pixijs/pixi-display#40]
I was wondering, because of migration issues, if there will be support for pixi v5 when it's released?

**Comment by ivanpopelyshev** [comment]
As soon as pixi-v5 beta.1 gets released. soon.

**Comment by ivanpopelyshev** [comment]
Btw, if you use only zIndex inside single container, v5 has it in the package.

**Comment by jkanchelov** [comment]
Thanks for the fast and helpful response.
