### ISSUE TITLE
Sharing sprite between two layers?

### ISSUE THREAD

**Issue by sonal71** [pixijs/pixi-display#42]
I am trying to create a mesh that has layers of series of sprites both horizontal and vertical.

![image](https://user-images.githubusercontent.com/3215717/52502021-b952e700-2baf-11e9-941f-6b8d57fece99.png)

All the boxes are sprites. I have two layer L1 and L2. And there is one sprite shared between two layers.

But looks like the common sprite can only belong to either L1 or L2.

Is there a way to share sprite between two layers?

Thank you in advance! :)

**Comment by ivanpopelyshev** [comment]
That's a strange case. What will be behaviour of pixi-display in that case according to your idea? Suppose element has two parentLayers, how do you think it will be rendered?

**Comment by sonal71** [comment]
Thinking this through it does seem a bit strange. More or less it looks like layers for fixed positions rather than specific sprites.
Will work on it to see if I find something.
Thank you!
