### ISSUE TITLE
Could pixi-display cause event propagation issues?

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi-display#7]
I'm hunting an event propagation issue, even though I don't .stopPropagation, the event doesn't bubble under an entity

I've created a small test case, however, in the test case, event bubbles as expected

I'm just wondering whether the way pixi-display shuffles entities could cause the event issue I'm experiencing

**Comment by ivanpopelyshev** [comment]
Yes, it has its own interaction cycle. Please look inside and tell me if there's something wrong in it , compared to original pixi code.

**Comment by kaansoral** [comment]
Sorry, I only just managed to replicate the issue, replied on https://github.com/pixijs/pixi.js/issues/2921#issuecomment-245039445

If you want we can move the discussion here
