### ISSUE TITLE
Some (lots) of items disappear in internet explorer

### ISSUE THREAD

**Issue by robbeman** [pixijs/pixi-display#8]
Very strange: some items just disappear completely in internet explorer. Don't know exactly why, but it seems to be related to the zOrder property.

The elements disappearing al have a zOrder lower then ~180, elements with a higher zIndex seem to work. (I'm calculating zIndex by distance from the bottom of the screen)

I've attached two screenshots, one in chrome and another, from the same game, in IE (11).
<img width="645" alt="screenshot chrome" src="https://cloud.githubusercontent.com/assets/3245659/18869627/696b0980-84ad-11e6-8e9a-cc9c191a4f15.png">
![screenshot ie](https://cloud.githubusercontent.com/assets/3245659/18869628/696c1f14-84ad-11e6-8bc1-a5b4015ee031.png)

Anyway, I don't have more information right now, I'll probably look further into it later. (Maybe I'm doing something strange, I dunno)

**Comment by robbeman** [comment]
I've looked further into this issue and it seems that the cause was `sprite.cacheAsBitmap = true;`
I only had this on elements with zOrder, so I wrongly assumed it had to do with that.

So I'm closing the issue. Sorry for bothering.

**Comment by ivanpopelyshev** [comment]
Hello! Sorry for late answer :) I happy that you resolved it
