### ISSUE TITLE
pixi-display or pixi-layers

### ISSUE THREAD

**Issue by DennisSmolek** [pixijs/pixi-display#9]
Hey Ivan, 

I've stumbled upon this library when trying to do some work to create a image/content editor with Pixi as the rendering engine. Basically Fabric.js/Illustrator but with Pixi for the WebGL. 

I was going to write a lot of my own stuff but I saw the pixi-layers branch and all the great work/demos that went into that. Great job and docs too!

I then also saw that pixi-display had a few commits as well. Are you forking the projects? The way the pixi-layers readme reads pixi-layers has a more advanced version of pixi-display in it. 

I'm going to start with pixi-layers as a starting point but I'd like to know/understand your plans moving forward and if in my using this library I can be of any help.

**Comment by ivanpopelyshev** [comment]
There is only one commit, I deleted something. Yes, its better to start with pixi-layers.
